### ISSUE TITLE
[BUG] "Reset Notification Position" doesn't reset it to default, but to the middle of wherever the settings window is

### ISSUE THREAD

**Issue by OnlYKai** [radj307/volume-control#100]
### Version

6.2.0-rev1

### Windows Version

Windows 11 Pro Version 22H2

### Actual Behaviour

"Reset Notification Position" button doesn't reset it to the default position, but to the middle of wherever the settings window is
![image](https://github.com/radj307/volume-control/assets/67548894/3659cc87-e353-4873-9f67-9cde0b8b49f5)

### Expected Behaviour

pressing the reset button resets it to the botton right corner where it's by default

**Comment by radj307** [comment]
Fixed in cb916abcc3cccdef8688eac604b1239f74ec0b13
