### ISSUE TITLE
Change session to new app's PID on reboot

### ISSUE THREAD

**Issue by hiroweeb** [radj307/volume-control#102]
I play modded games and sometimes have to relaunch the game (multiple times) to tweak/repair stuff. 
A feature that allows Volume Control to hook onto the new app's PID (based on process name/executable?) if it was in focus before its restart would be dope.

**Comment by radj307** [comment]
This already exists - if your currently selected session has the wrong PID (such as when it restarts) it will be automatically resolved when you press a hotkey.

If this isn't working correctly, please let me know.
