### ISSUE TITLE
[BUG] Version 6.4.0 - Strings untranslated

### ISSUE THREAD

**Issue by bovirus** [radj307/volume-control#110]
### Version

6.4.0

### Windows Version

Windows 10 22H2 64bit italian

### Actual Behaviour

Strings untranslated (see red boxes)

![image](https://github.com/radj307/volume-control/assets/1262554/39874a00-f90a-49b9-82d1-d5f5279dcbe3)

![image](https://github.com/radj307/volume-control/assets/1262554/63d9176c-12bd-41d5-a999-c76efa47d89c)

![image](https://github.com/radj307/volume-control/assets/1262554/af91b8ed-fbc3-4fd2-ae1f-d15260dbf412)

### Expected Behaviour

Please add in language file the relative strings

### Reproduction Steps

Check the options in screenshot

**Comment by radj307** [comment]
Added support for translating addon actions in 053f85a965e3c454727be68be78d6d4dd60e18d2

Translations for the default actions are in `VolumeControl.HotkeyActions/Localization`, and use a slightly different naming scheme *(appended `-HotkeyActions` to the locale ID)*.  
I created `it-HotkeyActions.loc.json` so you don't have to mark it as an embedded resource yourself.

**Comment by radj307** [comment]
Added support for translating default hotkey names in 75a28b7c40c8521d439019b813913fcfd47a04aa

The names will not update unless you reset the hotkeys to default after changing the language, however. There is no way around this, but hotkeys can always be renamed.

**Comment by radj307** [comment]
This issue has been fixed and is now available in [`v6.5.0`](https://github.com/radj307/volume-control/releases/tag/6.5.0).
