### ISSUE TITLE
[BUG] Cant open the app it starts loading and nothing

### ISSUE THREAD

**Issue by Dimetro25** [radj307/volume-control#112]
### Version

6.4.0

### Windows Version

Windows 10 Pro version 22H2 OS Build 19045.3570

### Actual Behaviour

When I click it it starts loading for a second and then stops that's it

### Expected Behaviour

It is supposed to open the app

**Comment by radj307** [comment]
Some questions:
1. Did you use the installer or are you using the portable version?
2. Is your Windows language set to German?
3. Does the problem occur when using [`v6.4.0-dbg1`](https://github.com/radj307/volume-control/suites/17730372567/artifacts/1015167898)?  
   Extract that archive somewhere & try using the executables in there. If you see an update prompt, ignore it.

**Comment by Dimetro25** [comment]
Hello, I did use the installer. I am on v6.4.0(not sure about -dbg1). My Windows language is set to English

**Comment by radj307** [comment]
Try the `6.4.0-dbg1` version I linked:  
https://github.com/radj307/volume-control/suites/17730372567/artifacts/1015167898

#101 was having a similar problem with the installer version and this fixed it.

**Comment by Dimetro25** [comment]
Thanks for the fast respond I will download it and tell you if it works right away

**Comment by Dimetro25** [comment]
Yes, it worked Thanks for everything

**Comment by radj307** [comment]
Good to hear! The next release (`6.5.0`) will incorporate those changes, it'll be out in the next day or so.

**Comment by Dimetro25** [comment]
Thanks btw can it run in the background?

**Comment by radj307** [comment]
Yes, when you minimize the main window it'll go into the system tray so you can just use the hotkeys.

**Comment by Dimetro25** [comment]
OO yea thanks

**Comment by Dimetro25** [comment]
Hello there I have another problem. After I got the new updates 5 and 6 the run at start doesn't work
