### ISSUE TITLE
Add version number to Installer executable filename

### ISSUE THREAD

**Issue by nospaulatu** [radj307/volume-control#117]
Whenever I download an updated version of the installer, the new file is named VolumeControl-Installer(8).exe, VolumeControl-Installer(9).exe, VolumeControl-Installer(10).exe, etc...

It would be nice if the file name included the version number to tell them apart easily. For example, the latest release could be VolumeControl-Installer-6.5.1.exe

Thanks!

**Comment by radj307** [comment]
No problem! Added in e24aefec1d10b9fdddf53ca2a45de026d3668527, the new installer name will be used by the next release.

**Comment by radj307** [comment]
Now available as of [`v6.5.2`](https://github.com/radj307/volume-control/releases/tag/6.5.2)
