### ISSUE TITLE
[FEATURE] Show Notifications window when Active Application hotkeys are used

### ISSUE THREAD

**Issue by nospaulatu** [radj307/volume-control#118]
I mainly use VolumeControl with the Active Application hotkeys to avoid having to fiddle with selecting sessions. I have hotkeys for Active Application Volume Up and Down, and Toggle Mute.

It would be nice if a notification window popped up to show the state of the active application whenever those hotkeys are pressed. Show the current volume and mute state of the active application.

**Comment by radj307** [comment]
I do intend to implement this.  
This is a fairly simple change, but it can have a lot of unintended consequences so it may take some time to debug it.

In the meantime, you can work around this by enabling **Select Session** in the action settings for the Active Application actions. This will cause notifications to appear for the active application, but will change your current session/add it to your selected sessions.

**Comment by nospaulatu** [comment]
That workaround works like a charm, thanks!

**Comment by Dregu** [comment]
I also wanted this feature, but selecting the sessions was not a good option, so I took a stab at making a real active apps only notification. I don't really know anything about WPF, but seemed simple enough to tweak the existing session template to draw from an alternative list while such list exists. This branch is built on top of my PR branch dealing with similar stuff, and I might merge them later. https://github.com/Dregu/volume-control/tree/active-notification
