### ISSUE TITLE
[BUG] Installer strings in Inno Setup script

### ISSUE THREAD

**Issue by bovirus** [radj307/volume-control#119]
### Version Number

6.5.1

### File

Installer  (VolumeControl-Installer.exe)

### Windows Version

Windows 10 22H2 64bit Italian

### Actual Behaviour

Currently yuou changed the copyright string in

AppCopyright=Copyright © {#CurrentYear} {#AppPublisher}

"copyrighT" and "©" are synonims:
Copyright is already the field name of this descrition then the fulls string fieldname+description is

Copyright: Copyright © {#CurrentYear} {#AppPublisher}

Three times the copyright terms.

My idea is that the copyright message should be like before

AppCopyright=© {#StartYearCopyright}-{#CurrentYear} {#AppPublisher}

Thanks.

### Expected Behaviour

Restroe original message

**Comment by radj307** [comment]
Readded date range in 1f5c4041339af2c5d7d2fb9ed48edf4cdf12daec

The message now reads `Copyright © 2022-2023 radj307`, which will be the final copyright notice string.
