### ISSUE TITLE
[FEATURE] Auto Updater

### ISSUE THREAD

**Issue by Rajdave69** [radj307/volume-control#124]
An auto updater for the installer-based app

**Comment by radj307** [comment]
Implemented for the installer version in 195cf26edf030e4b4ce2c0da95f5933521889b71.

**Comment by radj307** [comment]
The "auto-updater" in this case does the following:  
1. Prompt the user about a new update being available.
2. When the user clicks 'Yes', download the latest installer to the default downloads directory.
3. Start the installer
4. Close the application

**Comment by radj307** [comment]
Now available in [v6.6.0](https://github.com/radj307/volume-control/releases/tag/6.6.0)
