### ISSUE TITLE
[BUG] Doesn't Auto select Spotify at startup

### ISSUE THREAD

**Issue by Dimetro25** [radj307/volume-control#130]
### Version Number

6.6.2

### File

Installer  (VolumeControl-Installer.exe)

### Windows Version

Windows 10 Pro version 22H2 OS Build 19045.3570

### Actual Behaviour

Before when I started my pc the app launched and when I opened Spotify it automaticlly selected it. Now I think that's from 5.5 and up it doesn't select Spotify, I have to do it manually

**Comment by radj307** [comment]
Can you paste the value of `TargetSession` in your config file at the following points:  
1. With VC & Spotify open, when Spotify is selected.
2. After closing VC.
3. After starting VC with Spotify still open.

*Note: You can open the config file when VC is open by R+Clicking on the system tray icon and clicking **Open Config**, or by pressing Win+R & entering `%localappdata%/radj307/volumecontrol/volumecontrol.json`.*

`TargetSession` can be found near the bottom of the file, and looks like this:  
```json
  "TargetSession": {
    "PID": 21032,
    "ProcessName": "Deezer",
    "SessionInstanceIdentifier": "{0.0.0.00000000}.{9d2749b4-7c0d-434f-955b-0187eefc59c5}|\\Device\\HarddiskVolume3\\Users\\Administrator\\AppData\\Local\\Programs\\deezer-desktop\\Deezer.exe%b{00000000-0000-0000-0000-000000000000}|1%b21032"
  },
```

Use this template for your reply (copy/paste):

\#\#\# 1
\`\`\`json
<-- `TargetSession` from step 1 goes here
\`\`\`

\#\#\# 2
\`\`\`json
<-- `TargetSession` from step 2 goes here
\`\`\`

\#\#\# 3
\`\`\`json
<-- `TargetSession` from step 3 goes here
\`\`\`

**Comment by Dimetro25** [comment]
Here you go I think I did it right

### 1
```json
"TargetSession": {
    "PID": null,
    "ProcessName": "Spotify",
    "SessionInstanceIdentifier": ""
  },
```

### 2
```json
"TargetSession": {
    "PID": null,
    "ProcessName": "Spotify",
    "SessionInstanceIdentifier": ""
  },
```

### 3
```json
 "TargetSession": {
    "PID": null,
    "ProcessName": "Spotify",
    "SessionInstanceIdentifier": ""
  },
```

**Comment by radj307** [comment]
From looking at the first one, it seems like Spotify wasn't actually selected, in that, it wasn't open.  
Will definitely need a log file to be able to diagnose this further.

**Comment by Dimetro25** [comment]
HH:mm:ss:fff              === Log Initialized @ Sunday, November 26, 2023 2:46:06 PM ===  { LogFilter: 62 (INFO, WARN, ERROR, CRITICAL, FATAL) }
16:46:06:776  [INFO]      Changed application working directory to 'C:\Users\dimit\AppData\Local\Programs\VolumeControl' (Was 'C:\Windows\system32').
16:46:06:790  [INFO]      Config version is 0.0.0, settings will be migrated to version 6.6.2.
16:46:07:541  [INFO]      Volume Control version 6.6.2 (Installed)
16:46:07:647  [INFO]      Microsoft Windows 10 Pro (64-bit)

I just started my PC and it works as normal but still here's the log

**Comment by radj307** [comment]
This isn't enough to determine anything, I'll need a full log with all log levels enabled *(Settings -> Event Logging -> Filter -> check all of the boxes)* from a time that the bug you're describing occurred.

**Comment by radj307** [comment]
Is this issue still occurring for you?

**Comment by Dimetro25** [comment]
No. As I said in my last reply it fixed itself. I guess I didn't select it properly the first time

**Comment by radj307** [comment]
In that case, closing this
