### ISSUE TITLE
[BUG] Difficult to follow changes to translation config files

### ISSUE THREAD

**Issue by bovirus** [radj307/volume-control#132]
### Version

6.6.3

### Language

Italian

### Problem

@radj307
You many times changes the order of strings and sometimes make massive changes to the structure of language strings.
Many times it's very difficult to follow you and maintained updated translations.
In last language update you made many changes that require a new check from scratch.
And it is not the first time this has happened.
Please consider if you can use a different translation system that can help translators to made a not so big job.
Thanks.

**Comment by radj307** [comment]
I was actually just thinking about this. I've been wanting to make some kind of unified way to report changes to translation configs so maintainers can be notified of changes *(and changelogs can be updated accordingly)*. I did update the [contributing translations wiki page](https://github.com/radj307/volume-control/wiki/Contributing-Translations) for the addition of what I'm calling "single-language syntax", so you may want to check there to get up to speed with how that works.

I plan to create a github actions script that tracks changes to all of the translation configs using git, then compile a list of those changes for translation maintainers. That way it would be **much** easier to see what changes were made & what to do about them. Hopefully it'd be possible to allow people to subscribe to notifications too, so they don't have to go out of their way to figure out if a change was made.

Additionally, I've been chipping away at a [GUI editor program for translation config files](https://github.com/radj307/Localization.Editor/) to help with this too. It's still pretty early in development, but that also means it's still pretty malleable so if you have any feature requests I'd be happy to try and incorporate them into the final product. Currently all it really does is load translation configs, allow you to save them in any of the supported formats, and provide a visual tree view of the file's contents *(you can use it to edit files too, but it isn't very easy to do that yet)*.

**Comment by radj307** [comment]
Another thing I should have mentioned is that you can use a regular expression to convert the translation configs.

This picture is of Visual Studio's find & replace tool, but it works in the same way as VS Code's (& the github editor): ![image](https://github.com/radj307/volume-control/assets/1927798/54233460-93d4-482a-a258-0ccc4fc8b46b)

For the search expression, use:  
`(".+?"):\s*{\s*\n\s*"Italiano \(Italian\)": (".+")\s*\n\s*}`  
And for the replacement expression, use:  
`$1: $2`

Once you've done that, add this line: `"$LanguageName": "Italiano (Italian)"` above the `"VolumeControl"` key.

In VS Code, press **Ctrl+F**

**Comment by radj307** [comment]
Update:  
- Created issue #133 to track changes to translation configs.  
- Added a github actions workflow that is triggered whenever a translation config file is modified & create a comment showing the changes & ping the commit's author to write about how to update the other translation configs.

Translation maintainers can subscribe to the changelog issue to receive notifications whenever a change is made to any translation config files. This could still use some refinement, however. Comments currently aren't cleaned up so this could quickly become extremely long and annoying to scroll through.

**Comment by radj307** [comment]
Closing as completed. See #134 for translation config updates in the future.
