### ISSUE TITLE
[BUG] Notification popup not appearing on all multiple desktops

### ISSUE THREAD

**Issue by teadrinker2015** [radj307/volume-control#154]
I noticed that notification popups are not shown on every desktop instances. (cycling with `win`+`ctrl`+`arrow key`)

**Comment by radj307** [comment]
I'm not able to reproduce this, but you may be able to fix it temporarily by switching to a desktop where notifs do appear and doing the following:
1. Press `Win`+`Tab` to open the desktop switcher
2. Press a hotkey to make the notification window appear
3. R+Click on the notification window and check "Show on all desktops"

**Comment by teadrinker2015** [comment]
I actually realized several days ago, that the notification window does not show immediately, if you just adjusted the volume from an another window instance. So it's rather an interaction issue, not a bug.
