### ISSUE TITLE
Two Spotify's 

### ISSUE THREAD

**Issue by Dimetro25** [radj307/volume-control#187]
Two Spotify's appear in the menu. It might be because I use Spicetify. Is there a way to select the specific apps that are with the name Spotify?

**Comment by TBonexdd** [comment]
https://github.com/radj307/volume-control/issues/185#issuecomment-2350001243

Look at my Solution, it could fix it for you as well.

**Comment by Dimetro25** [comment]
@TBonexdd do you happen to use spicetify?🤔

**Comment by TBonexdd** [comment]
Nope, I use the original Spotify setup from the official website, but the 32-Bit version

**Comment by Dimetro25** [comment]
What's the difference between the 64 one and the 32

**Comment by TBonexdd** [comment]
The Operating System you use. But I have a 64 Bit OS and use the 32 Bit Spotify, there is only one Spotify instance in volume control

**Comment by Dimetro25** [comment]
Yea I mean is there any difference between the two like performance wise or compatability?

**Comment by TBonexdd** [comment]
I dont think so. As I can tell both of them are pretty much the same.

**Comment by Dimetro25** [comment]
Ok thank you very much for the help 🙂

**Comment by TBonexdd** [comment]
No problem, I hope it works!
