### ISSUE TITLE
Multilanguage GUI

### ISSUE THREAD

**Issue by bovirus** [radj307/volume-control#30]
@radj307 

Thanks for your software.

Could you pelase consdier to imporve source code to have multilanguage GUI?

Thanks.

**Comment by radj307** [comment]
Support for this will be added in 5.2.1

**Comment by radj307** [comment]
Added in [v5.2.1](https://github.com/radj307/volume-control/releases/5.2.1)  

See [#31](https://github.com/radj307/volume-control/discussions/31) for more information on creating and consuming UI language configs.
