### ISSUE TITLE
[BUG] 5.2.1 - GUI issues

### ISSUE THREAD

**Issue by bovirus** [radj307/volume-control#32]
@radj307 

Using Italian language I found some issues.

Please check screenshot

![image](https://user-images.githubusercontent.com/1262554/183241125-6dc39ce6-ae20-44e7-92dc-c693b248ae09.png)

Some strings are untranslated.
Move from main settings json file to language json file.

The width of "Maiusc" coulmn is too small.
Please enlarge main window width and increase space for "Maiusc" column.

**Comment by bovirus** [comment]
![image](https://user-images.githubusercontent.com/1262554/183241145-ff8ec199-25e6-43f1-9a84-e3c4eafb3655.png)

The width of "Seleziona" button is too small.
Please enlarge main window width and increase space for "Seleziona" button.

**Comment by bovirus** [comment]
![image](https://user-images.githubusercontent.com/1262554/183241198-a705b31d-f34a-44f8-8e19-ccfc4c1f35d8.png)

"On volume change" seems not translated (but is translated in language file).

Move "Update" option left on the elft and right ion the right.
Then you can increase space for central option about update.

**Comment by bovirus** [comment]
![image](https://user-images.githubusercontent.com/1262554/183241990-bf4a99a4-df88-4d20-bcb0-93056f1518a6.png)

In system control tray there are three strings not localzied and not included in language file.

**Comment by bovirus** [comment]
**About tab.**

I beilieve that could be inetersting to have an "About" tab that show information about program name and version and link about website and support link.

**Comment by radj307** [comment]
> **About tab.**
> 
> I beilieve that could be inetersting to have an "About" tab that show information about program name and version and link about website and support link.

I moved this to its own issue

**Comment by radj307** [comment]
5.2.2 will have support for translating the notify icon:  
![](https://user-images.githubusercontent.com/1262554/183241990-bf4a99a4-df88-4d20-bcb0-93056f1518a6.png)

I'm hesitant to make each of the options that verbose, as it can use up a lot of space very quickly; I can, however, add a header with the program name & version number to the top to provide some context

**Comment by radj307** [comment]
I increased the amount of padding in the select buttons, which will be included in 5.2.2:  
> ![image](https://user-images.githubusercontent.com/1927798/183253734-98db738f-5659-4d94-a6ab-b2e2f37552ee.png)

I also increased the margins in the Settings -> Update section, which will also be included in 5.2.2

**Comment by radj307** [comment]
Hotkey name & action identifier translations will take some more time to implement, since it has to be compatible with the addons system.  
I'll most likely be implementing hotkey/action translations in separate files, that way addon developers can distribute their own translations along with the addon dlls.

**Comment by bovirus** [comment]
@radj307 

Update italian language.
Please check and merge and release new application version.

If you can please check also this request

https://github.com/radj307/volume-control/issues/36

**Comment by radj307** [comment]
Please limit issue reports to the actual issue being reported.  

GUI bugs have been fixed in [5.2.2](https://github.com/radj307/volume-control/releases/5.2.2)
