### ISSUE TITLE
[FEATURE] About tab

### ISSUE THREAD

**Issue by radj307** [radj307/volume-control#35]
_Originally posted by @bovirus in https://github.com/radj307/volume-control/issues/32#issuecomment-1207177526_

# About Tab

I believe it could be interesting to have an "About" tab to show information about the program, like the name and current version, as well as links to the issues *(support)* page.

**Comment by radj307** [comment]
This will be added in 5.2.2

**Comment by bovirus** [comment]
@radj307 

Thanks.

Are you refer to 5.2.3 (5,2,2 was relased 5 days ago)?

**Comment by radj307** [comment]
I was, whoops! am very tired

**Comment by radj307** [comment]
I've decided not to add a whole about tab since I was struggling to fill it to the point of actually justifying a whole tab since the program name and version number are already shown on the caption bar.  

Instead, I added a new button to the caption bar with a 'bug' icon *(lady [**beetle**](https://unicode-table.com/en/1F41E/), not ladybug!)* that takes you to the bug report / support page, and added a hyperlink to the version number that takes you to the github repository.  
Additionally, I've added some feedback indicators for these buttons to make it obvious that they are actually clickable.

For the time being, I just commented out the XAML code for the about tab rather than deleting it in case something comes up later that would justify using the extra space.

**Comment by radj307** [comment]
The above is now available in [v5.2.3](https://github.com/radj307/volume-control/releases/5.2.3)

**Comment by radj307** [comment]
Some additional things to add to the about tab:
- Contributor names & credits, sorted by contribution category *(ex. Code, Translations, Resources like icons & fonts, etc.)*
- Built-in submission form for bug reports *(?)*
- The release date of the current version

**Comment by radj307** [comment]
Closing this as it isn't necessary
