### ISSUE TITLE
[Question] How to use Language Configs in a portable installation

### ISSUE THREAD

**Issue by bovirus** [radj307/volume-control#36]
@radj307 

How can setup, or change the source code to search automatically language .json file ins ame folder where I run Volume Control?

This enable a portable use of the application.

**Comment by radj307** [comment]
# Language Configs

You can accomplish this by specifying a relative path for the `CustomLocalizationDirectories` setting in `VolumeControl.json`.    

To load any language configs located in the same directory as `VolumeControl.json`:  
```json
  "CustomLocalizationDirectories": [
    "."
  ],
```

`.` specifies the current working directory.  

See [here](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats) for more information on Windows filepaths.
