### ISSUE TITLE
[BUG] Tooltips not showing for some settings

### ISSUE THREAD

**Issue by StormingChaos** [radj307/volume-control#45]
### Version

5.2.3

### Actual Behaviour

Hovering over "Show in taskbar" and "Always on top" shows the name of the variable instead of the actual tooltip. 
![image](https://user-images.githubusercontent.com/57851464/184551679-2c49a117-5c75-44ad-9456-81bf1e8779d9.png)

Brand new installation on computer that has never installed volume control

**Comment by StormingChaos** [comment]
Fixed in 93837fd097b715fd063cab687320bcb8f0d3a845

**Comment by radj307** [comment]
### Implementation

This was fixed for the `ToolTip` control *specifically* by adding a `DataTrigger` to a global style that sets `Visibility="Hidden"` when the `Content` property is set to `" "`. Then, we changed all occurrences of `DefaultText=''` within translation markup to `DefaultText=' '`, which overrides the translation markup extension's default behaviour of using the translation path, which were the malformed tooltip messages in the image.
