### ISSUE TITLE
[BUG] 5.2.4-1 - Button width not enough

### ISSUE THREAD

**Issue by bovirus** [radj307/volume-control#47]
### Version

5.2.4-1

### Actual Behaviour

Button width is not enought for text

![image](https://user-images.githubusercontent.com/1262554/185377076-1e566ac9-065f-44cb-be54-826fbe6bcb06.png)

### Expected Behaviour

Button width larger

**Comment by radj307** [comment]
Fixed in [v5.2.4-2](https://github.com/radj307/volume-control/releases/tag/5.2.4-2) and onwards
