### ISSUE TITLE
[FEATURE] Ability to Control Multiple Programs At Once

### ISSUE THREAD

**Issue by FroobTubeLIVE** [radj307/volume-control#54]
(sorry if it seems like I'm spamming, I just brushed up on the rules and this seems to be the more "appropriate" place to suggest features/ideas)

Like I said on my last post on the "discussion" page, it would be an absolute power move if you were able to make it so that you can control multiple programs at the same time, instead of having to cycle through "sessions". As well as instead of being relegated to the "multi-instance" option.

Cheers

**Comment by radj307** [comment]
I'm open to implementing this.

It would be fairly easy to add the ability to specify multiple applications as targets, but it does raise some questions as to how this would work.  
I could add the ability to specify multiple target applications in the current target box by separating them with semicolons `;`, or add the ability to create a list of target box*es*.  

Let me know what you think.

**Comment by FroobTubeLIVE** [comment]
Thanks for the consideration! I was definitely thinking more along the lines of your latter suggestion, where you can specify hotkeys for specific applications.

I've made a mock-up version of the gist what I have in mind; in my pic attached I've merged the "Mixer" and "Hotkeys" tabs :) (feel free to laugh at the ridiculous resizing of things)

![radj307 volumecontrol feature add on idea suggestion thing lol](https://user-images.githubusercontent.com/121452612/210094967-a277e05f-00e8-4d6d-8cf9-ffd87daf58dd.png)

**Comment by radj307** [comment]
As of 0ef5d4267e8ea9d8d7b45f4c215730c2d1bb0477 a rudimentary 'settings' interface has been added for hotkeys. It currently only supports strings/numbers *(anything that you can enter into a textbox)*, but this will eventually be expanded to support selecting items from a list.

Here is a screencap of the hotkeys tab:  
![image](https://user-images.githubusercontent.com/1927798/210654704-410dd11c-01ea-4e83-ab3f-8dba8769a46f.png)  
![image](https://user-images.githubusercontent.com/1927798/210655515-e7022f14-04e5-4b24-9cf1-d4a37ed6394c.png)  
Settings are unique to each hotkey:  
![image](https://user-images.githubusercontent.com/1927798/210654797-39c46292-6816-4830-b73b-891f1b7e7c1b.png)  ![image](https://user-images.githubusercontent.com/1927798/210655071-4e0ab9e7-edf8-4493-a334-dc595a1e29b0.png)  

Next steps:
1. Implement a selector control that supports lists
2. Implement a template selector so the action settings window uses the correct control for the variable type
3. Update existing actions so they can take advantage of this
    - **Device** actions should all support specifying any number of audio devices
    - **Session** actions should all support specifying any number of audio sessions
4. Polish the GUI

***

*Note to self: Update the SDK documentation to introduce action developers to the new settings feature.*

![image](https://user-images.githubusercontent.com/1927798/210657801-577cba00-8b2f-4a64-a213-c7993a90c15d.png)

**Comment by FroobTubeLIVE** [comment]
So from what little coding I understand (basically none), it looks like you've merged the "target applications" with the hotkeys themselves? Correct me if I'm wrong, which I easily could be lol

**Comment by radj307** [comment]
It's important to remember that hotkeys and actions are two distinct things in Volume Control, and you can have any number of hotkeys that all use the same action *(such as `TEST1` & `TEST2` both using the `Session: Action Setting Test Function` action)*. I designed it like this with the intention of adding action configuration in the first place, but never actually got around to it before.  

Once it's fully implemented, you'll be able to do something like this:  
![image](https://user-images.githubusercontent.com/1927798/211126048-935f35f2-776a-4fad-ba0e-c5c9065d8452.png)

**Comment by FroobTubeLIVE** [comment]
Well I'm looking forward to it, my man! (and everyone else involved in the project!)

**Comment by radj307** [comment]
Working implementation as of 104bf54700a4c9ca4c549d751bdb867a5902e578 / 92556b0f1619e711dfa8644463ba33af47569d47:  
![vc-actionsettings2](https://user-images.githubusercontent.com/1927798/211937972-55d6e0b8-ac43-474c-b6e9-6f186cd97136.gif)

Using settings:  
![image](https://user-images.githubusercontent.com/1927798/211937383-10fc7383-7aac-4c9f-82b7-cb077dedf59b.png)
![image](https://user-images.githubusercontent.com/1927798/211937421-c56e41d8-3794-4833-a55d-beedbea5b22c.png) ![image](https://user-images.githubusercontent.com/1927798/211937437-244201b9-1ca7-40fd-a079-b314ea12d041.png) ![image](https://user-images.githubusercontent.com/1927798/211937496-6323432d-3fdf-4016-904c-7b32061df2d9.png) ![image](https://user-images.githubusercontent.com/1927798/211937521-bf4857f5-059c-4316-b848-2ef62d7b7994.png)

Next steps:  
1. Finish implementing this for other hotkey actions
2. Polish up the action settings menu

**Comment by FroobTubeLIVE** [comment]
Incredibly pogged up, thank you so much for your hard work 🙏 You guys are absolute legends 💚

**Comment by radj307** [comment]
Thank you! 👍 

I have a preview prerelease ready that includes customizable `Session`-group actions:  
https://github.com/radj307/volume-control/releases/tag/6.0.0-rc1  
Please try it out and let me know what you think!

**Comment by radj307** [comment]
Thanks for the feedback!

My reasoning for not integrating the mixer & hotkey tabs is that it would require extensive changes to the existing codebase; something I'd be more comfortable approaching by re-designing the application rather than a simple update.  
I wholeheartedly agree that "Edit Mode" has outlived its purpose, and it has been removed as of 164a00aec35236badad0987e9b641c054e3f24f8.

On the subject of contact methods, I don't really have any social media to speak of; but you can contact me via email at radj307@gmail.com

**Comment by radj307** [comment]
Closing this as the requested feature has been implemented. Further enhancements to this feature are being tracked in #64.
