### ISSUE TITLE
Add app selection instead of showing all apps

### ISSUE THREAD

**Issue by Kr4k3n10rd** [radj307/volume-control#56]
Hi there,
I was thinking if it would be possible to modify what apps are visible in the app selection menu that appears; instead of showing all apps running in the background/playing audio, would it be possible to choose 1 or 2 that are visible, so that I don't need to scroll through apps that I never change the volume of?
Thanks!

**Comment by homealone944** [comment]
Bump. Was just thinking this would definitely be a nice to have. Sometimes theres too many apps in the menu (like multiple discord processes) and would be nice to cut down on them.

**Comment by radj307** [comment]
Closing this in favour of #68, which has now been implemented.
