### ISSUE TITLE
[FEATURE] Visual for AudioDevice control

### ISSUE THREAD

**Issue by homealone944** [radj307/volume-control#58]
When using Hotkeys for Device, it is confusing as to which device I am currently changing, and its current volume. It would be nice to have visuals like for Sessions

**Comment by radj307** [comment]
This has been addressed somewhat in [6.0.0 Preview 5](https://github.com/radj307/volume-control/releases/6.0.0-pr5)

**Things that could still be improved on:**
- Automatic switching between display targets.

**Comment by radj307** [comment]
This was removed in 6.0.0 Preview 7.

It will be reimplemented in a future preview release. In the meantime, I've left 6.0.0 Preview 6 up on the releases page for anyone that still wants to use this feature.

**Comment by radj307** [comment]
Feature implemented in f4202a4f41eb903544e156dab53f8aaa89350db2.

Now available in v6.0.0
