### ISSUE TITLE
Hotkeys with scrolling

### ISSUE THREAD

**Issue by homealone944** [radj307/volume-control#59]
Would be nice to have ability to use scroll wheel directions in Hotkeys. IE: Alt+scroll up can be volume up, and Alt+scroll down is volume down. 

Under Keys I see "Scroll" but after testing with it, I cant get it to work.

**Comment by radj307** [comment]
AFAIK, this isn't possible because the Win32 API doesn't support mouse scroll up/down as "keys".

The problem is explained in more detail here: https://github.com/radj307/volume-control/issues/42
