### ISSUE TITLE
Change Volume of Active Application

### ISSUE THREAD

**Issue by muffinimal** [radj307/volume-control#60]
I have a macropad with two Volume Knobs on it. I want to use those knobs to control:
- discord
- the game I am currently playing
- (I use my keyboard's volume controls for global volume)

Volume Control seems really cut out to help me in this, but I can't seem to set it up as it depends on sessions to control volume. The way I am imagining things is that I set up Volume Control like this:
- create two shortcuts for the session (vol+, vol-) (discord)
- create two shortcuts for the current application (my current game)

I figure there are multiple ways to resolve this (per application shortcuts for example), but I guess this is sufficient for me.

Volume2 (https://github.com/irzyxa/Volume2) supports 'active application'. So far I have only been able to get what I want by running both programs. Not quite a permanent solution, I guess.

I'd wish I could contribute, but I have zero experience in c#.

**Comment by radj307** [comment]
Implemented active-application-specific actions as of c19a22b0212d8dccb12df6ab9ea2ae191a96bce0

Things that could still be improved:
- Notification window does not appear when changing active application volume/mute state. *(This is much harder to fix than it may seem)*

**Comment by radj307** [comment]
I backported this feature to v5.2.5 as an addon.

 1. Download & extract this archive: [Addon.ActiveApplicationActions.dll.zip](https://github.com/radj307/volume-control/files/11106188/Addon.ActiveApplicationActions.dll.zip)  
 2. Place `Addon.ActiveApplicationActions.dll` in `.../AppData/Local/radj307/Addons` *(create any missing directories)*

You can quickly open the `.../AppData/Local` directory by pressing Win+R and entering `%localappdata%`

**Comment by muffinimal** [comment]
Great stuff! Thanks for getting back this fast!

Sadly I need to report that the addon doesn't seem to do anything. I set the addon up, bound some hotkeys to Active Application Volume, enabled them. And... Nothing happens.

So, I am on 5.2.5 on Windows 11. Nothing of note in the logs (set to DEBUG). Tried rebooting.

**Comment by radj307** [comment]
Make sure you activate the window you're trying to control first. The easiest way to do that is to just click on the window.  
This technique _should_ work with pretty much any window that outputs audio, but please let me know if it doesn't work for something specific. *(I imagine Discord probably doesn't play nice with this)*

![active](https://user-images.githubusercontent.com/1927798/228871840-c375c0eb-b2dd-4047-aa68-e2f26c4d9d99.gif)

**Comment by muffinimal** [comment]
Tried with Google Chrome mostly. I probably checked behaviour of volume of
other apps as well. Quite sure I had focus. Will try some other apps when I
get back to desktop.

If you want, I'll be happy to show you in discord.  Thanks for the quick
reply!

Op do 30 mrt. 2023 16:42 schreef radj307 ***@***.***>:

**Comment by muffinimal** [comment]
Yes, you're quite right. The addon doesn't work in Chrome, but it does in Firefox. I do get a
`[WARN]   Session '7500:chrome' doesn't exist; searching for near-matches...`

I think those warnings are at startup, though.

I have tried your rc. What I am trying to achieve can be done by using the targets, however. I should play with some multi-processes, though. It is slightly a bit more hassle to setup as you need to provide multiple targets. Got a release-date for it set yet? I can fiddle around to see if I find anything else.

**Comment by radj307** [comment]
I improved the robustness of searching for applications by falling back to searching for the foreground application's process name.

Try replacing the other DLL with this one: [Addon.ActiveApplicationActions.dll.zip](https://github.com/radj307/volume-control/files/11117103/Addon.ActiveApplicationActions.dll.zip)

**Comment by radj307** [comment]
Included in 6.0.0-pr3 (Preview 3) and up
