### ISSUE TITLE
[BUG] Hotkey Target Override no longer works in Preview 3

### ISSUE THREAD

**Issue by FroobTubeLIVE** [radj307/volume-control#63]
### Version

6.0.0-pr3

### Actual Behaviour

This version is very broken since the last release (6.0.0-rc1), as I am incapable of controlling multiple applications/sessions simultaneously, and am only able to control ANYTHING if I have a specific session "Selected" in the Mixer tab.

### Expected Behaviour

I understand that this is a "preview release", but so was rc1, and that version works as needed, so there's something missing between then and now.

### Reproduction Steps

1. Open program
2. Go into "Hotkeys" tab
3. Delete any unwanted/cluttered hotkeys (the bottom 3)
4. With "Volume Up", "Volume Down", and "Toggle Mute" as remaining options, edit the "Key" to the desired key for each; from top to bottom: NumPad2, NumPad1, NumPad0. Again, for VolUp, VolDown, and Toggle Mute respectively.
5. Assign "Alt" as the only modifier for each key.
6. Check ON all 3 keys by using the left checkbox column selector
7. Click the tool icon/Target Override, and add my primary internet browser (LibreWolf) as the only application for both Volume Up and Volume Down.
8. Set Google Chrome ("chrome") as the only source for "Toggle Mute"
9. Go back into Mixer tab and attempt using hotkeys.
10. Nothing changes at all.
11. Click "Select" on either of my applications while in the Mixer tab
12. Hotkeys work but only for the selected application, since it was "selected" in this section, and not "added" in the Target Override.

### Log

```shell
HH:mm:ss:fff           === Log Initialized @ April 2, 2023 6:13:54 PM ===  { Filter: 30 (ALL_EXCEPT_DEBUG) }
14:13:55:811  [ERROR]  Hotkey 1 unregistration failed:  'Hot key is not registered.' (HRESULT: 1419)
14:13:55:812  [ERROR]  Hotkey 2 unregistration failed:  'Hot key is not registered.' (HRESULT: 1419)
14:13:55:813  [ERROR]  Hotkey 3 unregistration failed:  'Hot key is not registered.' (HRESULT: 1419)
14:13:55:813  [ERROR]  Hotkey 4 unregistration failed:  'Hot key is not registered.' (HRESULT: 1419)
14:13:55:814  [ERROR]  Hotkey 5 unregistration failed:  'Hot key is not registered.' (HRESULT: 1419)
14:13:55:814  [ERROR]  Hotkey 6 unregistration failed:  'Hot key is not registered.' (HRESULT: 1419)
14:13:55:820  [INFO]   Volume Control v6.0.0-pr3
14:17:49:946  [ERROR]  Hotkey 1 registration failed:  'Hot key is already registered.' (HRESULT: 1409)
14:17:49:947  [ERROR]  Hotkey 2 registration failed:  'Hot key is already registered.' (HRESULT: 1409)
14:17:49:947  [ERROR]  Hotkey 3 registration failed:  'Hot key is already registered.' (HRESULT: 1409)
14:22:07:426  [INFO]   Session selected: '15820:chrome' ({0.0.0.00000000}.{7125a004-daab-499d-9b8e-07658374c6ce}|\Device\HarddiskVolume2\Program Files\Google\Chrome\Application\chrome.exe%b{00000000-0000-0000-0000-000000000000}|10%b15820)


Log for version rc1:

HH:mm:ss:fff           === Log Initialized @ April 2, 2023 6:27:28 PM ===  { Filter: 30 (ALL_EXCEPT_DEBUG) }
14:27:30:756  [INFO]   Volume Control v6.0.0-rc1
14:27:58:400  [ERROR]  Hotkey 3 unregistration failed:  'Hot key is not registered.' (HRESULT: 1419)
14:27:58:404  [ERROR]  Hotkey 2 unregistration failed:  'Hot key is not registered.' (HRESULT: 1419)
14:27:58:407  [ERROR]  Hotkey 1 unregistration failed:  'Hot key is not registered.' (HRESULT: 1419)
14:27:58:491  [INFO]   App exited with code 0
```

**Comment by radj307** [comment]
[Preview 4](https://github.com/radj307/volume-control/releases/6.0.0-pr4) is now available.

**Comment by FroobTubeLIVE** [comment]
Ah truly epic indeed
