### ISSUE TITLE
[FEATURE] Drop-Down Menu for "Target Override"

### ISSUE THREAD

**Issue by FroobTubeLIVE** [radj307/volume-control#64]
Love everything you guys have done so far. Just wanted to also suggest a drop-down menu within the Hotkeys' "Target Override" option, as this would be an exponential leap in streamlining things, making it hands-down the most accessible option out there, period.

With a drop-down menu displaying every available source right off the bat, there would also be no need to refer to the Mixer tab, and thus no concerns about typing anything incorrectly if someone feels the need to resort to that instead of copying & pasting from the Mixer tab for whatever reason. And again, it would just be soooooooooo dang fast.

If you are to consider such an implementation, it should also have a lil something to let people know it's a drop-down, instead of remaining completely blank when nothing is selected. Like text that says "-- Select --" or a small down arrow on the right side, or maybe both—something that's quick and obvious.

Thanks!

**Comment by radj307** [comment]
Added autocomplete for entering target overrides in 6435eeffc0ae476435a8e6dc24a5e1a92e85e433

**Comment by radj307** [comment]
Made the process of adding target overrides much smoother in bc523ef851e88b23aedc9febb4a64aed4025056a & cc37b261bf5ec40592b70ec3e465b756a7e9b0ef
![target-overrides-demo](https://github.com/radj307/volume-control/assets/1927798/00b9fce5-5cc6-4b8f-94f7-818b06d5293f)

The `+` button was replaced with a TextBox with autocomplete. Pressing Enter will accept the current suggestion and add it to the target overrides list. This makes adding audio sessions to the target overrides list much faster and more accurate.

**Comment by radj307** [comment]
Fully implemented in ff0529611f4d5ca8b77588c2e7936159e37471f1 & a89efb0ffacb0cac58ac7486ba5e176fc1b25601.

This feature will be included in the next (preview) release.

Next steps:
- Make this reusable and implement it for #68 as well
