### ISSUE TITLE
Change placement of the toast on the screen/another screen

### ISSUE THREAD

**Issue by hiroweeb** [radj307/volume-control#67]
My setup currently has two monitors (one being vertical) and have a lot of stuff on my second monitor while I play, and some games don't let the toast through. 

My current workaround is to have VolumeControl on top of the second monitor all the time, but the UI can't be resized so when programs with an audio process pile up, I have to play Tetris with my windows to be able to fit stuff I "need" (say a wiki page, chat platforms or browser pages you're keeping an eye on).

I'd love to move the toast on the middle left of my main screen (or vertical screen and minimize the program) to only cover Discord/my browser when I use hotkeys, but programming isn't my strong suit.

**Comment by radj307** [comment]
This feature is currently available in the v6 beta.  

However a few severe bugs remain in v6 that are preventing its release, so I don't recommend using it yet. (See #65)
