### ISSUE TITLE
[FEATURE] Ability to remove programs from the mixer list

### ISSUE THREAD

**Issue by Jeremy2131** [radj307/volume-control#68]
### Discussed in https://github.com/radj307/volume-control/discussions/66

<div type='discussions-op-text'>

<sup>Originally posted by **Jeremy2131** April 23, 2023</sup>
Hello, huge thanks for your program
By my suggestion I mean can we be able to remove unnecessary programs from the mixer tab 
I have for example 2 discord instances, telegram, sharex and viber which I would never volume control and between them sometimes I can find my games or chrome so I need to do additional presses on my hotkey to move to that program, it's like just saving few seconds but..</div>

**Comment by radj307** [comment]
I like this idea.

**Comment by radj307** [comment]
Implemented in 043abebe453bdfd044e4baa148252ec99542dbca

The interface for hiding/unhiding sessions needs some work, but the basic functionality is there *(ignore the weird UI appearance)*:  
![hidden-sessions-demo](https://github.com/radj307/volume-control/assets/1927798/36852a8d-39fd-4372-b7df-ad908049bfa4)

**Comment by radj307** [comment]
This feature is now available as of 6.0.0 Preview 9
