### ISSUE TITLE
[BUG] The Hotkey editor is missing many keys

### ISSUE THREAD

**Issue by nospaulatu** [radj307/volume-control#70]
### Version

5.2.5

### Actual Behaviour

When setting up Hotkeys, the user is presented with a drop-down menu to select which key to configure. This menu is missing several common keys from a standard QWERTY keyboard.

For example, many punctuation keys are not available, such as [ ] , . / \ ; ' `
Some navigation keys are missing, such as PgUp and PgDown

### Expected Behaviour

The application should allow the user to set up a Hotkey with any key available on their keyboard.

### Reproduction Steps

1. Open the Hotkeys tab in the Volume Control application
2. Create a new Hotkey or edit an existing Hotkey
3. Click on the Key drop-down menu to select which key to configure
4. Try to set up Ctrl-Alt-[ and Ctrl-Alt-] for Volume Down and Up for example

**Comment by radj307** [comment]
Fixed in d12426a1c7b0a66480d38071bb1d826d1fb75812

**Comment by radj307** [comment]
Now available in preview release [`v6.0.0-pr6`](https://github.com/radj307/volume-control/releases/tag/6.0.0-pr6)
