### ISSUE TITLE
[BUG] ... swapping audio output breaks the program

### ISSUE THREAD

**Issue by RobbyZzRobby** [radj307/volume-control#72]
### Version

5.1.2

### Actual Behaviour

the program works perfect but when i swap the sound from my headset to my speakers the program breaks. so the sound changes only work for the device i was using when starting up the app. I can use the speakers by just restarting the app but, it would be awesome if you were able to find the issue, maybe even adding the abbility to swap audio output in the app itself would help to fix thiss. ( if you do this please add shotcut availaibilty to it :) )

**Comment by StormingChaos** [comment]
This is related to #65, to solve it we would have to change to a completely different audio library which will take a lot of work. We are planning to fix this, but it will take a while. Thanks for the suggestion on switching audio devices!

**Comment by radj307** [comment]
Closing as duplicate.

**Comment by radj307** [comment]
This should be fixed now that #65 has been resolved.
