### ISSUE TITLE
Changing volume on the fly with scroll wheel

### ISSUE THREAD

**Issue by Ebi12054j1** [radj307/volume-control#76]
Can I request 'changing volume on the fly by just hovering my mouse and scrolling on one of the slider'?

I love your work, but the problem is I can't keep switching the desired app I want to change my volume with my keyboard.
I always keep this app on my second screen, so I can change it on the fly, but I can't even use scrollwheel on the slider.

**Comment by radj307** [comment]
Thanks for the suggestion!

Implemented in d4daf9d2666b2894f0eb594c931e0308bd2ba5c4

**Comment by radj307** [comment]
**This feature is now available in [6.0.0 Preview 7](https://github.com/radj307/volume-control/releases/tag/6.0.0-pr7).**

**Comment by Ebi12054j1** [comment]
Thank you! It's working great😃

**Comment by radj307** [comment]
No problem! 👍 

Also added support for editing NumericUpDown controls *(such as the Volume Step editor box)* with the mouse wheel in 07686b92bcc33c73f2625b6dd6a879713edfcb25
