### ISSUE TITLE
Windows Defender detects 6.0.0 Preview 9.1 VolumeControl.exe as virus

### ISSUE THREAD

**Issue by NominalWasTaken** [radj307/volume-control#78]
I download the exe file from the 6.0.0 Preview 9.1 and attempted to execute it but windows defender removed it. The installer file however did not cause any red flags.
![image](https://github.com/radj307/volume-control/assets/134882520/02efceb6-65ec-4645-8a16-eec264c8004e)

**Comment by radj307** [comment]
I have submitted the v6.0.0 executable to [Microsoft Security Intelligence](https://www.microsoft.com/en-us/wdsi/filesubmission) for review.  

This problem should be fixed within a couple days.

**Comment by radj307** [comment]
Closing as resolved. Let me know if you have any further issues.
