### ISSUE TITLE
[BUG] Audio adjustment "not working"

### ISSUE THREAD

**Issue by OnlYKai** [radj307/volume-control#80]
### Version

6.0.0

### Windows Version

Windows 11 Pro Version 22H2

### Actual Behaviour

If Volume Step is set to 1 and you press the button to lower it, it will still show 1, but it will be set to 0 and thus doesn't adjust the volume

### Expected Behaviour

Not being able to lower it to 0, or show it as 0, to prevent confusion

**Comment by radj307** [comment]
Fixed in 7ab2131b80a0abe4376fc97f08849828adf997ff & b2f09cfdedfe2efc91c446d81c12a39b213ae840

**Comment by radj307** [comment]
Now available in [v6.0.2](https://github.com/radj307/volume-control/releases/tag/6.0.2)
