### ISSUE TITLE
[BUG] The "Application: Unminize" hotkey doesn't work with "Start Minimized"

### ISSUE THREAD

**Issue by OnlYKai** [radj307/volume-control#81]
### Version

6.0.0 (I think 5.2.5 had the same problem)

### Windows Version

Windows 11 Pro Version 22H2

### Actual Behaviour

When the program starts minimized you can't use the unminimize hotkey until you unminimize it by clicking on it with your mouse.
(volume up/down do work even if it starts minimized btw)

### Expected Behaviour

the unminimize hotkey working on minimized start

### Reproduction Steps

bind an "Application: Unminize" hotkey
activate "Start Minimized" in settings
close it
start it
press the hotkey (doesn't work)
unminimize it with the tray icon
minimize it with the minimize (-) button
try the hotkey again (does work)

**Comment by radj307** [comment]
Fixed in 20654841946ff423074beeb4faa4202de8825115

**Comment by radj307** [comment]
Now available in [v6.0.2](https://github.com/radj307/volume-control/releases/tag/6.0.2)
