### ISSUE TITLE
[FEATURE] Auto-select target override

### ISSUE THREAD

**Issue by radj307** [radj307/volume-control#92]
### Discussed in https://github.com/radj307/volume-control/discussions/89

<div type='discussions-op-text'>

<sup>Originally posted by **JavierL742** October  8, 2023</sup>
Hello, i like this app a lot, and i appreciate your work. Thank you for what you are doing.

This is one feature i would like to see. Example photo:

![image](https://github.com/radj307/volume-control/assets/67005972/5486d966-f4ed-4269-b67d-8924e0b6c0b1)

Regards and thank you once more👋</div>

Select target override automatically when a hotkey is pressed.

**Comment by radj307** [comment]
I'll address this when I wake up tomorrow.

**Comment by radj307** [comment]
Implemented in da1cefe3916a7bd3a0522c9fb6c5c9740feac4fa

**Comment by radj307** [comment]
This feature is now available in [v6.1.0](https://github.com/radj307/volume-control/releases/tag/6.1.0).

**Comment by radj307** [comment]
Implemented in 1c1f964841fcfcc6e059c4e91facf2fe674c079a for the following actions:
- Active Application: Volume Up
- Active Application: Volume Down
- Active Application: Mute
- Active Application: Unmute
- Active Application: Toggle Mute

**Comment by radj307** [comment]
This will be included in the next release (already made 2 releases td). In the meantime, you can download the build artifact directly:
https://github.com/radj307/volume-control/suites/17388068401/artifacts/993699675

**Comment by JavierL742** [comment]
Amazing, thank you once again.

Today i read the guide for the translation, i will translate it to spanish.

Have a good night!

**Comment by radj307** [comment]
You too!
