### ISSUE TITLE
Is there a way to make this have hotkeys for specific applications?

### ISSUE THREAD

**Issue by Rajdave69** [radj307/volume-control#93]
I want it to always have two keys for vol up/down for spotify, two other keys for my browser, is that possible?

**Comment by radj307** [comment]
Yes, you can use the Target Overrides feature to accomplish this.  

1. Create 2 new hotkeys for Spotify volume up/down
2. Click the settings icon next to each of the new hotkeys
3. In the **Target Overrides** box, type "Spotify" and press enter.

This will let you adjust spotify's volume while also adjusting other applications with the default volume up/down hotkeys.
