### ISSUE TITLE
[FEATURE] Per-hotkey volume step

### ISSUE THREAD

**Issue by Rajdave69** [radj307/volume-control#94]
A per-hotkey setting for volume step.

For example,
The first hotkey named "test" has volume step 1
The second hotkey named "test2" has volume step 5

This would be a useful feature, for global volume I'd like to have step 1 and for applications 2, that's an example use case.

**Comment by radj307** [comment]
This would be fairly straightforward to implement as an action setting.

**Comment by radj307** [comment]
Implemented in da1cefe3916a7bd3a0522c9fb6c5c9740feac4fa

**Comment by radj307** [comment]
This feature is now available in [v6.1.0](https://github.com/radj307/volume-control/releases/tag/6.1.0).
