### ISSUE TITLE
[FEATURE] More toast customization

### ISSUE THREAD

**Issue by Rajdave69** [radj307/volume-control#95]
I would like to suggest the addition of more customization options to the toast when a hotkey is triggered.

An option to select what all will be shown in the toast seems useful, for example for the toast's items, 
- `only volumebar`
- `volumebar and selected item` 
- `volumebar with all items` (the full current toast) 

Below are examples to what each of them could look like - 

Only volumebar
![image](https://github.com/radj307/volume-control/assets/86198810/21fac94f-5e0a-486e-be98-7d30e4d41910)

Volumebar and selected item
![image](https://github.com/radj307/volume-control/assets/86198810/638c3a2c-91c7-4b96-93c4-a066a52710ed)

Volumebar with all items 
![image](https://github.com/radj307/volume-control/assets/86198810/a47ea4e8-6110-4c5b-9905-924134e74078)
(current toast)

**Comment by Rajdave69** [comment]
Also it would be nice having a toast for active application too

**Comment by radj307** [comment]
Implemented customizable toast notifications in 0902c0f1823b2dbff43d9028b5b4d25c712d44d0

**Comment by radj307** [comment]
Added in [v6.4.0](https://github.com/radj307/volume-control/releases/tag/6.4.0)

**Comment by Rajdave69** [comment]
@radj307 it would be nice if there was a toast when changing volume of current application with a hotkey
