### ISSUE TITLE
[FEATURE] Set specific volume level with a hotkey

### ISSUE THREAD

**Issue by AgenB** [radj307/volume-control#97]
I have a silly use-case for this app - I use it only to change the volume of the Deezer Windows app when I'm in-game and don't want to alt-tab, since Deezer doesn't support global key shortcuts, but otherwise when I'm not playing anything, I keep the app's volume at 100% and use Deezer's slider.
Instead of going back to the desired volume level by holding down the shortcut, I'd like to just tap once to reach the desired volume.

**Comment by radj307** [comment]
I could certainly add an action that sets the volume level of specified sessions to a pre-configured value.

I do have to ask, why use Deezer's volume slider rather than just hotkeys in the first place? Deezer not having hotkeys is actually the reason I made volume control in the first place.

**Comment by radj307** [comment]
Implemented in da1cefe3916a7bd3a0522c9fb6c5c9740feac4fa

**Comment by radj307** [comment]
This feature is now available in [v6.1.0](https://github.com/radj307/volume-control/releases/tag/6.1.0).

**Comment by AgenB** [comment]
Thank you very much for the quick update! And to answer your question - hotkeys are assigned to my keyboard's knob, but when I'm lazy and only keeping my hand on my mouse, it's quicker to just click on Deezer and change the volume :P
